development:
  adapter: async
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pcf9c5b13fb37cd2a1c40ddd23281c061576ed266fb2a8dd189d5f39feeb145b0@ec2-54-208-76-96.compute-1.amazonaws.com:64329
